spring.datasource.url=jdbc:postgresql://dpg-d8o1r58k1i2s73ae3f3g-a.singapore-postgres.render.com/moneymanager_nqnq
spring.datasource.username=moneymanager_nqnq_user
spring.datasource.password=dT2cepFIERHCrMlnXF5zpQ4NSM3s7vNj